package meta

const (
	Mysql_Int         = "int"
	Mysql_Varchar     = "varchar"
	Mysql_Decimal     = "decimal"
	Mysql_Datetime    = "datetime"
	Mysql_Blob        = "blob"
	Mysql_Binary      = "binary"
	Mysql_Long_Blob   = "longblob"
	Mysql_Medium_Blob = "mediumblob"
	Mysql_Tiny_Blob   = "tinyblob"
	Mysql_Var_Binary  = "varbinary"
	Mysql_Date        = "date"
	Mysql_Time        = "time"
	Mysql_Timestamp   = "timestamp"
	Mysql_Year        = "year"
	Mysql_BigInt      = "bigint"
	Mysql_Double      = "double"
	Mysql_Float       = "float"
	Mysql_Json        = "json"
	Mysql_Text        = "text"
	Mysql_Set         = "set"
	Mysql_Bool        = "boolen"
)
