package tpl

const (
	Table = `package {package_name}

// Code generated by orm. 
// DO NOT EDIT!!!
// DO NOT EDIT!!!
// DO NOT EDIT!!!
// Orm version: {orm_version}
// Database: {database}
// Table: {table_name} {table_comment}
// Created time: {created_date}

import(
	"context"

	"github.com/kovey/db-go/v2/sql/meta"
	"github.com/kovey/db-go/v2/sql"
	"github.com/kovey/db-go/v2/model"
	"github.com/kovey/db-go/v2/table"
	"github.com/kovey/db-go/v2/itf"
	"github.com/kovey/pool"
	"github.com/kovey/pool/object"
{imports}
)

const (
	Table_{name} = "{table_name}" {table_comment}
{column_const}
)

func init() {
	pool.DefaultNoCtx("ko.tables.{package_name}", "{name}Table", func() any {
		return &{name}Table{ObjNoCtx: object.NewObjNoCtx("ko.tables.{package_name}", "{name}Table"), Table: table.NewTable[*{name}Row](Table_{name})}
	})
	pool.DefaultNoCtx("ko.tables.{package_name}", "{name}Row", func() any {
		return &{name}Row{ObjNoCtx: object.NewObjNoCtx("ko.tables.{package_name}", "{name}Row")}
	})
}

{table_comment}
type {name}Table struct {
	*object.ObjNoCtx
	*table.Table[*{name}Row]
}

func New{name}Table() *{name}Table {
	return &{name}Table{Table: table.NewTable[*{name}Row](Table_{name})}
}

func New{name}TableBy(ctx object.CtxInterface) *{name}Table {
	return ctx.GetNoCtx("ko.tables.{package_name}", "{name}Table").(*{name}Table)
}

func (self *{name}Table) Reset() {
	self.InTransaction(nil)
}

func (self *{name}Table) FetchAll(where meta.Where) ([]*{name}Row, error) {
	return self.Table.FetchAll(where, &{name}Row{})
}

func (self *{name}Table) FetchAllByWhere(where sql.WhereInterface) ([]*{name}Row, error) {
	return self.Table.FetchAllByWhere(where, &{name}Row{})
}

func (self *{name}Table) FetchBySelect(sel *sql.Select) ([]*{name}Row, error) {
	return self.Table.FetchBySelect(sel, &{name}Row{})
}

func (self *{name}Table) FetchPage(where meta.Where, page, pageSize int, orders ...string) (*meta.Page[*{name}Row], error) {
	return self.Table.FetchPage(where, &{name}Row{}, page, pageSize, orders...)
}

func (self *{name}Table) FetchPageByWhere(where sql.WhereInterface, page, pageSize int, orders ...string) (*meta.Page[*{name}Row], error) {
	return self.Table.FetchPageByWhere(where, &{name}Row{}, page, pageSize, orders...)
}

func (self *{name}Table) FetchAllCtx(ctx context.Context, where meta.Where) ([]*{name}Row, error) {
	return self.Table.FetchAllCtx(ctx, where, &{name}Row{})
}

func (self *{name}Table) FetchAllByWhereCtx(ctx context.Context, where sql.WhereInterface) ([]*{name}Row, error) {
	return self.Table.FetchAllByWhereCtx(ctx, where, &{name}Row{})
}

func (self *{name}Table) FetchBySelectCtx(ctx context.Context, sel *sql.Select) ([]*{name}Row, error) {
	return self.Table.FetchBySelectCtx(ctx, sel, &{name}Row{})
}

func (self *{name}Table) FetchPageCtx(ctx context.Context, where meta.Where, page, pageSize int, orders ...string) (*meta.Page[*{name}Row], error) {
	return self.Table.FetchPageCtx(ctx, where, &{name}Row{}, page, pageSize, orders...)
}

func (self *{name}Table) FetchPageByWhereCtx(ctx context.Context, where sql.WhereInterface, page, pageSize int, orders ...string) (*meta.Page[*{name}Row], error) {
	return self.Table.FetchPageByWhereCtx(ctx, where, &{name}Row{}, page, pageSize, orders...)
}

{table_comment}
type {name}Row struct {
	*object.ObjNoCtx
	*model.Base[*{name}Row]
{row_fields}
}

func New{name}Row() *{name}Row {
	self := &{name}Row{Base: model.NewBase[*{name}Row](New{name}Table(), model.NewPrimaryId({primary_id}, model.{primary_id_type}))}
	{close_auto_inc}
	return self
}

func New{name}RowBy(ctx object.CtxInterface) *{name}Row {
	self := ctx.GetNoCtx("ko.tables.{package_name}", "{name}Row").(*{name}Row)
	if self.Base == nil {
		self.Base = model.NewBase[*{name}Row](New{name}TableBy(ctx), nil)
	}
	if self.Base.Table == nil {
		self.Base.Table = New{name}TableBy(ctx)
	}
	self.Base.SetPrimaryId(model.NewPrimaryIdBy(ctx, {primary_id}, model.{primary_id_type}))
	{close_auto_inc}
	return self
}

func (self *{name}Row) Reset() {
	self.Base.Reset()
{row_fields_reset}
}

func (self *{name}Row) Clone(ctx object.CtxInterface) itf.RowInterface {
	return New{name}RowBy(ctx)
}

func (self *{name}Row) Columns() []string {
	return []string{
{func_columns}
	}
}

func (self *{name}Row) Fields() []any {
	return []any{
{func_fields}
	}
}

func (self *{name}Row) Values() []any {
	return []any{
{func_values}
	}
}

func (self *{name}Row) Save() error {
	return self.Base.Save(self)
}

func (self *{name}Row) FindByInt(id int64) error {
	return self.FetchRow(meta.Where{self.PrimaryId(): id})
}

func (self *{name}Row) FindByIntCtx(ctx context.Context, id int64) error {
	return self.FetchRowCtx(ctx, meta.Where{self.PrimaryId(): id})
}

func (self *{name}Row) FindByString(id string) error {
	return self.FetchRow(meta.Where{self.PrimaryId(): id})
}

func (self *{name}Row) FindByStringCtx(ctx context.Context, id string) error {
	return self.FetchRowCtx(ctx, meta.Where{self.PrimaryId(): id})
}

func (self *{name}Row) FetchRow(where meta.Where) error {
	return self.Base.FetchRow(where, self)
}

func (self *{name}Row) LockByInt(id int64) error {
	return self.LockRow(meta.Where{self.PrimaryId(): id})
}

func (self *{name}Row) LockByIntCtx(ctx context.Context, id int64) error {
	return self.LockRowCtx(ctx, meta.Where{self.PrimaryId(): id})
}

func (self *{name}Row) LockByString(id string) error {
	return self.LockRow(meta.Where{self.PrimaryId(): id})
}

func (self *{name}Row) LockByStringCtx(ctx context.Context, id string) error {
	return self.LockRowCtx(ctx, meta.Where{self.PrimaryId(): id})
}

func (self *{name}Row) LockRow(where meta.Where) error {
	return self.Base.LockRow(where, self)
}

func (self *{name}Row) Delete() error {
	return self.Base.Delete(self)
}

func (self *{name}Row) SaveCtx(ctx context.Context) error {
	return self.Base.SaveCtx(ctx, self)
}

func (self *{name}Row) FetchRowCtx(ctx context.Context, where meta.Where) error {
	return self.Base.FetchRowCtx(ctx, where, self)
}

func (self *{name}Row) LockRowCtx(ctx context.Context, where meta.Where) error {
	return self.Base.LockRowCtx(ctx, where, self)
}

func (self *{name}Row) DeleteCtx(ctx context.Context) error {
	return self.Base.DeleteCtx(ctx, self)
}
	`
	Field = "	%s %s `db:\"%s\"` %s"

	Decimal                  = `	"github.com/shopspring/decimal"`
	Sql                      = `	ds "database/sql"`
	Meta_Column              = `		%s,`
	Meta_Fields              = `		&self.%s,`
	Meta_Values              = `		self.%s,`
	Close_Auto_Inc           = "self.NoAutoInc()"
	Field_Reset_Str          = `	self.%s = ""`
	Field_Reset_Num          = `	self.%s = 0`
	Field_Reset_Bool         = `	self.%s = false`
	Field_Reset_Decimal      = `	self.%s = decimal.Zero`
	Field_Reset_Nil          = `	self.%s = nil`
	Field_Reset_Sql_Null     = `	self.%s = ds.Null%s{}`
	Field_Reset_Decimal_Null = `	self.%s = decimal.NullDecimal{}`
)
