package tpl

const (
	Table = `package {package_name}

// Code generated by orm. 
// DO NOT EDIT!!!
// DO NOT EDIT!!!
// DO NOT EDIT!!!
// Orm version: {orm_version}
// Database: {database}
// Table: {table_name}
// Created time: {created_date}

import(
	"github.com/kovey/db-go/v2/sql/meta"
	"github.com/kovey/db-go/v2/model"
	"github.com/kovey/db-go/v2/table"
{imports}
)

type {name}Table struct {
	*table.Table[*{name}Row]
}

func New{name}Table() *{name}Table {
	return &{name}Table{Table: table.NewTable[*{name}Row]("{table_name}")}
}

type {name}Row struct {
	*model.Base[*{name}Row]
{row_fields}
}

func New{name}Row() *{name}Row {
	return &{name}Row{Base: model.NewBase[*{name}Row](New{name}Table(), model.NewPrimaryId("{primary_id}", model.{primary_id_type}))}
}

func (self *{name}Row) Save() error {
	return self.Base.Save(self)
}

func (self *{name}Row) FetchRow(where meta.Where) error {
	return self.Base.FetchRow(where, self)
}

func (self *{name}Row) Delete() error {
	return self.Base.Delete(self)
}
	`
	Field = "	%s %s `db:\"%s\"` // %s"

	Decimal = `	"github.com/shopspring/decimal"`
	Sql     = `	"database/sql"`
)
